name = "Brave New Globe"
author = "Minecraft-Bonanaza"
version = "0.7.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e33844f40cd342ba525b037f5fd480a879d019bca9c2b49d25d98993f0098e4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
