name = "Brave New Globe"
author = "Minecraft-Bonanaza"
version = "0.9.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0608c9c7e2bb902ef677ccf27f43616ff4b1a6aefa0ea52b6310affa81b91444"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
