name = "Brave New Globe"
author = "Minecraft-Bonanaza"
version = "0.9.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c6b6df9172f706352f1618438ea6a7ddb5cb8ae28f20513d17c1d2ceabc69b3"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"
